### ISSUE TITLE
Users sometimes not found

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/rse-sagemaker-shim#18]
Two occurrences:

` File \"sagemaker_shim/models.py\", line 302, in _get_user_info`

RuntimeError: User 1000 not found

RuntimeError: User 1001 not found

First one is from @pkcakeout, have requested the Dockerfile.

**Comment by jmsmkn** [comment]
The second is from a container that previously worked, so needs fixing.

**Comment by jmsmkn** [comment]
The Dockerfile:

```
FROM python:alpine3.17
COPY main.py /app.py
USER 1000
ENTRYPOINT [ "python3", "/app.py" ]
```

**Comment by pkcakeout** [comment]
My 2-cents, in case not obvious: `_get_user_info` likely tries to query the user-information for a user that was not actually created in my container. Linux allows to set the UID/GID of a process to any numeric number independent from the underlying system definitions for users. So while the container should work, `get_user_info` will not.

**Comment by jmsmkn** [comment]
The user is indeed not created, which is a problem for switching here.

We do some lookups to find what user (and group) to switch to as we always receive a string, and are not sure if this is a username or user id:

https://github.com/DIAGNijmegen/rse-sagemaker-shim/blob/a9852c55055e2a95db4497c3f984a2cf68a0d37f/sagemaker_shim/models.py#L292-L302

We then set the user info from this:

https://github.com/DIAGNijmegen/rse-sagemaker-shim/blob/a9852c55055e2a95db4497c3f984a2cf68a0d37f/sagemaker_shim/models.py#L318-L345

Before passing it to `create_subprocess_exec`:

https://github.com/DIAGNijmegen/rse-sagemaker-shim/blob/a9852c55055e2a95db4497c3f984a2cf68a0d37f/sagemaker_shim/models.py#L460-L467

Here the `user` and `group` will be handled by `subprocess.Popen`. AFAIK this does essentially the same checks with `getpwuid` so would fail there.

**Comment by pkcakeout** [comment]
Docs for the disambiguation issue: https://www.gnu.org/software/coreutils/manual/coreutils.html#Disambiguating-names-and-IDs

**Comment by jmsmkn** [comment]
Main question for me - does `Popen` allow passing `user=1000` when that user does not exist in the db? If so, then we only need to fix our code. If not, what is the Python interface for doing this?

**Comment by pkcakeout** [comment]
As long as you are root this seems to work as expected. You cannot do it as a "lower user" though, for obvious reasons...

~~~~~~~~~~
root@dingo-linux:/home/paul# python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.check_call(["id"])
uid=0(root) gid=0(root) groups=0(root)
0
>>> subprocess.check_call(["id"], user=21322)
uid=21322 gid=0(root) groups=0(root)
0
>>> subprocess.check_call(["id"], user=21322, group=32321)
uid=21322 gid=32321 groups=32321,0(root)
0
~~~~~~~~~~

**Comment by jmsmkn** [comment]
Great! Then we just need to fix our logic, no problem.

**Comment by jmsmkn** [comment]
Okay I think I have the fix, please take a look.

**Comment by pkcakeout** [comment]
Hey James!

Yes, you replicated what I did it seems, however, as you pointed out, we should probably still drop* the `extra_groups` so that the process does not have `root`-group permissions either.

*: Which brings me to the following headache when thinking about the state-space here: if we want to do it "perfectly well" we likely should do a lookup into the system groups config to see if there should be assigned to the user with the given uid (if it exists) and set `extra_groups` accordingly.

Though honestly I would only do this if we encounter any follow-up issues. I do not suspect the average deep-learning to go that much into the inner workings of Linux to get his project to work when working locally, so I suspect that all code we encounter in the wild will only need `uid` and `gid` assigned and the `extra_groups=[]`. So, I suggest:

~~~~~~.py
subprocess.check_call(["id"], user=21322, group=32321, extra_groups=[])
~~~~~~

for now.
